import json,gzip,math,statistics,hashlib,datetime
from pathlib import Path
BASE=Path('.pr4-state/audit-blind-20261009');OUT=Path('.pr4-state/independent-material-cases')
CASES=['PSSA3_2014','BBDC4_2014','CSMG3_2014']
ledger=[]
def read(p):
 b=p.read_bytes();ledger.append({'path':str(p),'sha256':hashlib.sha256(b).hexdigest(),'purpose':'Pacote primário, decisão congelada ou protocolo autorizado; sem resultados/retornos'});return b
def j(p):return json.loads(read(p))
def evidence(case,doc,group,pages,purpose):
 z=next(x for x in sources[case] if x['docid']==doc and x['group']==group)
 return {**{k:z[k] for k in ['docid','group','received','receipt_label','url','original_sha256']},'pages':pages,'purpose':purpose}
protocol=read(BASE/'protocol_v2_redacted.md')
inputs={};sources={};calc={}
for case in CASES:
 root=BASE/case;d=j(root/'decision.json');f=j(root/'financial_extract.json');sources[case]=j(root/'sources.json');manifest=j(root/'bundle_manifest.json');ip=j(root/'ipca_known.json');read(root/ip['known_may_availability']['original'])
 for s in sources[case]:
  raw=read(root/s['original']);assert hashlib.sha256(gzip.decompress(raw)).hexdigest()==s['original_sha256']
  jbytes=gzip.decompress(read(root/s['pages']));json.loads(jbytes)
 assert all(x['received']<=d['cutoff'] for rows in f.values() for x in rows)
 assert all(x['received']<=d['cutoff'] for x in sources[case])
 monthly={(int(x['data'][-4:]),int(x['data'][3:5])):float(x['valor']) for x in ip['sgs433_known_monthly_values']}
 fac={y:math.prod(1+r/100 for (yr,mo),r in monthly.items() if (yr,mo)>(y,12)) for y in range(2009,2014)}
 ni={};factrefs=[]
 for y in range(2009,2014):
  z=[x for x in f['facts'] if x['year']==y and x['perimeter']=='con' and x['account']==('3.09.01' if case.startswith('BBDC') else '3.11.01') and x['period_start']==f'{y}-01-01' and x['period_end']==f'{y}-12-31']
  x=max(z,key=lambda x:(x['received'],x['reference'],x['version']));ni[y]=x['value']*1000;factrefs.append(x)
 if case.startswith('PSSA'):adjusted={**ni,2013:703500000}
 elif case.startswith('BBDC'):adjusted={2009:-math.inf,2010:ni[2010]-79173000,2011:ni[2011]-2125714000-405983000-226711000-179028000-55356000-151446000,2012:ni[2012]-793360000,2013:-math.inf}
 else:adjusted={2009:-math.inf,2010:ni[2010]-334081000,2011:ni[2011]-29691000,2012:ni[2012]-60839000-7200000-7500000-12000000,2013:ni[2013]}
 real={y:adjusted[y]*fac[y] for y in adjusted};med=statistics.median(real.values());cap=sum(x['quantity']*x['price'] for x in d['capital_classes'])
 calc[case]={'reported_annual_ni':ni,'independent_adjustment_nominal':{y:(v if math.isfinite(v) else None) for y,v in adjusted.items()},'null_lower_means':'negative_infinity_not_zero','inflation_factors':fac,'real_values':{y:(v if math.isfinite(v) else None) for y,v in real.items()},'normalized_median_or_lower':med,'capitalization_recomputed':cap,'capital_classes':d['capital_classes'],'pe_or_pe_upper':cap/med,'minimum_profit_for_pe15':cap/15,'profit_headroom_real':med-cap/15,'fact_provenance':factrefs,'price_limitation':'Cotações de junho vieram de decision.json; nenhum original COTAHIST está no pacote para certificação independente do preço. Quantidades foram confrontadas com FRE capital emitido.','method':'Selecionar DRE consolidada anual atribuível mais recente recebida até corte; ajustar cada observação e multiplicar produto mensal SGS433 posterior a dezembro do exercício até maio/2014; calcular terceira ordem das cinco observações. Capital por classe própria. Código independente; não importou implementação.'}
 inputs[case]=d
p='PSSA3_2014';b='BBDC4_2014';c='CSMG3_2014'
reports=[
{'case':p,'audit_status':'PASS','severity':'LOW','admission_review':{'VVAL':'PASS_MATURE','VQ':'QUALIFIED_SATISFACTORY'},'conclusion':'Lucro recorrente atribuível2013 e capital prudencial têm suporte primário. P/L14,168997 recomposto. Não confundir lucro gerencial711m, lucro consolidado695,6m e atribuível703,5m; a compra via madura dispensa prêmio reinvestidor.','calculation':calc[p],
'favorable_evidence':[evidence(p,'34786',1653,[4,10,12,13],'Série atribuível e lucro recorrente703,5m, custos não recorrentes, dividendos e combinado96,0%'),evidence(p,'34786',412,[7,8,19,20,46,91,92],'Reapresentação, TAP provisionado38,192m, capital excedente1086,837m, aquisição pequena'),evidence(p,'36561',193,[4,28],'Excedente753,618m e garantia6584,740m para exigência6428,241m')],
'contrary_evidence':[evidence(p,'34786',412,[76],'COFINS líquido895,751m material; não basta subtrair da NI sem custos associados'),evidence(p,'36561',192,[3,4,15],'Combinado98,8%, sinistralidadeauto+4,1pp, benefícioCOFINS temporário2014;512m na holding não são excesso regulado'),evidence(p,'34786',412,[67],'PLR administradores152,355m contra75,555m requer monitoramento')],
'dimensions':{'durability':{'status':'SATISFACTORY','reason':'Renovações, marcas e rede de distribuição documentadas; concentraçãoauto/SãoPaulo e concorrência limitam qualidadeHIGH.'},'capital_economics':{'status':'SATISFACTORY','reason':'ROE recorrente703,5/[(5067,1+5187,4)/2]=13,720829%; com PL reportado=12,8419%. Combinado recorrente96%; receita financeira segue importante.'},'earnings_reliability':{'status':'SATISFACTORY','reason':'Ponte agregada recorrente atribuível explícita, TAP provisionado, ajustes auditados; não certificar711m como NI atribuível.'},'financial_resilience':{'status':'SATISFACTORY','reason':'Capital excedente positivo; queda30,66% no excedente e55,94% na cobertura técnica são riscos observados, não infração regulatória.'},'capital_allocation':{'status':'SATISFACTORY','reason':'Dividendos50%recorrente/70%extraordinário; investimento375,1m, aquisição32,17m pequena. Sem retorno incremental certificado.'},'governance':{'status':'SATISFACTORY','reason':'ON,tagalong100%, arbitragem, comitê independente e transações detalhadas. PLR/materialCOFINS não provam desvio.'}},
'additional_calculations':{'roe_adjusted_equity':703.5/((5067.1+5187.4)/2),'roe_reported_equity':703.5/((5067.1+5889.2)/2),'capital_excess_decline':1-753618/1086837,'technical_guarantee_surplus':6584740-6428241,'technical_guarantee_surplus_ratio':156499/6428241,'median_profit_nominal2013_tolerance':38974036.30828156},
'materiality':'Porto é a única seguradora elegível citada no protocolo na formação. Uma alteração na admissão afetaria presença setorial; não calculei pesos nem retornos. Lucro adicional removido de2013 acima38,974m poderia cruzar P/L15, até mudança de ordem da mediana.','specific_pending':['Monitorar trajetória do excesso de capital e cobertura técnica; não exigir limiar inventado.','Conferência de cotação COTAHIST fora do escopo do pacote.']},
{'case':b,'audit_status':'UNRESOLVED','severity':'HIGH','admission_review':{'VVAL':'INDETERMINATE_PENDING_IFRS_BRIDGE','VQ':'QUALIFIED_SATISFACTORY_WITH_LIMITATION_ON_EXACT_NORMALIZATION'},'conclusion':'A fórmula dos pisos e a mediana estão corretas, mas a neutralização do crédito/provisão2.911,634m está demonstrada no grupoBRGAAP, sem ponte quantitativa de reconhecimento para o lucro atribuívelIFRS usado no denominador. A decisão afirma reconciliação concluída; os originais incluídos sustentam natureza comum dos eventos, não igualdadeIFRS dos lançamentos. Não há reprovação fundamentalista comprovada.','calculation':calc[b],
'favorable_evidence':[evidence(b,'bradesco_2011_publication',0,[25,28,29],'BRGAAP grupo:2.911,634m crédito e provisão iguais;2.125,714m reversão;CPM79,173m/CETIP179,028m/Ibi55,356m;CSLL226,711m'),evidence(b,'15827',412,[81,125],'IFRSBERJ405,983m e residualIR151,446m'),evidence(b,'25736',412,[83,128,129],'IFRSSerasa793,360m e BERJ; perdas de crédito/impairment permanecem despesas'),evidence(b,'36377',193,[43,44,73],'Provisões e capitalBasileia15,7%,principal11,9%; não confundircursoanormal comNPL90')],
'contrary_evidence':[evidence(b,'bradesco_2011_publication',0,[29],'Publicação diz expressamente que demonstraçõesIFRS não fazem parte destasBRGAAP; expectativa de diferenças não significativas é declaração qualitativa da administração'),evidence(b,'15827',412,[81,84,116,117,118],'OutrasIFRS agregadas e provisões fiscais líquidas não individualizam a mesma neutralização2.911,634m'),evidence(b,'35965',412,[88,117],'IFRS compara2011 reapresentado e traz eventos materiais2013; não usar ganhos/perdas brutasNTN como lucro recorrente')],
'dimensions':{'durability':{'status':'SATISFACTORY','reason':'Franquia de depósitos/seguros/serviços e diversificação documentadas, sujeitas ao ciclo de crédito.'},'capital_economics':{'status':'SATISFACTORY_LIMITED','reason':'Operação bancária e seguradora lucrativa e absorção de perdas suportam qualidade satisfatória; ROE exato normalizado e pisoIFRS não certificados.'},'earnings_reliability':{'status':'SATISFACTORY_LIMITED','reason':'Perdas, renegociações e eventos divulgados; demonstrações críveis não implicam que todo lucro é recorrente. A lacuna da ponte bloqueia o piso deVVAL.'},'financial_resilience':{'status':'SATISFACTORY','reason':'Mar2014PR15,7%,principal11,9% contra exigência11%/4,5% da data; deduçõesprudenciais aumentaram e NívelII inclui dívida subordinada.'},'capital_allocation':{'status':'SATISFACTORY','reason':'Distribuição moderada, lucros retidos e manutenção de capital; aquisições e bônus não comprovam EPSorgânico/retornoincremental.'},'governance':{'status':'SATISFACTORY','reason':'Controles/partes relacionadas divulgados; concentração do controle e ON/PN diferentes preservados no capital. Sem prova primária de alerta estrutural não resolvido.'}},
'additional_calculations':{'profit_headroom_relative_to_lower':(calc[b]['normalized_median_or_lower']-calc[b]['minimum_profit_for_pe15'])/calc[b]['normalized_median_or_lower'],'extra_gain2011_nominal_to_exhaust_bound':(calc[b]['normalized_median_or_lower']-calc[b]['minimum_profit_for_pe15'])/calc[b]['inflation_factors'][2011],'if_full_credit2011_removed_without_IFRS_offset_pe_upper':calc[b]['capitalization_recomputed']/((7813816000-2911634000)*calc[b]['inflation_factors'][2011])},
'materiality':'Folga apenas0,382269% no piso real (R$34,599m), equivalendo aR$29,870mnominais2011. Uma diferença de reconhecimentoIFRS desse tamanho já derruba a prova do limite superior15, sem provar queP/Lverdadeiro>15. Por isso nova compraVVAL não está comprovada apenas pelo pacote.','specific_pending':['Tabela lançamentos2011 por entidade/evento que reconcilie crédito/provisão2.911,634mBRGAAP comIFRS atribuível, incluindo tributação/NCI/reapresentação.','Conferir ganhospositivos2010/2011/2012 que poderiam excederR$29,870m no ano2011 central; não adicionar perdas para fabricar piso.','Regularizar ressalva da decisão income_modes_reconciled=true até prova quantitativa.','Conferência de cotações de ambas classes no originalCOTAHIST.']},
{'case':c,'audit_status':'PASS','severity':'MEDIUM','admission_review':{'VVAL':'PASS_MATURE_BY_BOUND','VQ':'INDETERMINATE'},'conclusion':'A mediana de cinco limites inferiores é robusta e passa a via madura, sem atribuir P/L pontual. A indefiniçãoVQ tem causa efetiva em economia do capital/alocação, não payout35%,CAPEXalto ou FCLnegativo como filtros automáticos. Não há prova de negócio estruturalmente ruim.','calculation':calc[c],
'favorable_evidence':[evidence(c,'14868',412,[4,52,71],'Reversãoatuarial313,073m está dentro334,081m total2010;29,691m é reversãoconsolidada2011'),evidence(c,'24718',412,[84],'Reversãoconsolidada60,839m2012'),evidence(c,'34244',1653,[13,14,15,16,18],'PRODES7,2m,correçãoIR7,5m,PAT12m2012;custosPDV preservados, distribuição35%,dadosEPS/EBITDA'),evidence(c,'34244',412,[20,24,114],'Reapresentação2012 mantémNI481,723m;CFO669,408m;ICMS investigado sem autuação/provisãoexigível documentada')],
'contrary_evidence':[evidence(c,'34244',1653,[2,4,14,15],'CAPEX909,2m,EPS3,52vs4,04,EBITDAajustado+1,1%nominal e retorno7,9% não demonstram valorincremental'),evidence(c,'34244',412,[36,37,111],'SubsidiáriasPLnegativo86,346m;COPANORmútuo renegociado90%CDI e324meses por atraso de concessões'),evidence(c,'36764',192,[5,16],'Redução90%→50% tarifaesgoto e devoluções regulatórias atingem poderdepreço')],
'dimensions':{'durability':{'status':'SATISFACTORY','reason':'Demanda essencial, rede e concessões; tarifas/reembolsosARSAE limitam poderdepreço.'},'capital_economics':{'status':'INDETERMINATE','reason':'Expansão operacional documentada, mas lucroEPS eEBITDA real enfraquecem. Precisa explicar retorno regulado/entrada emoperação e custo econômico do capital; semWACCcertificado nem limiar universal deROE.'},'earnings_reliability':{'status':'SATISFACTORY','reason':'Reapresentação e lucros consolidados reconciliados; margem de construção sem caixa discriminada; não confundir opinião semressalva com prova de retornoincremental.'},'financial_resilience':{'status':'SATISFACTORY','reason':'Financiamento/projetos e covenants divulgados semviolação;CFO664,649m menor queinvestcash796,828m exige financiamento, não reprovação automática.'},'capital_allocation':{'status':'INDETERMINATE','reason':'CAPEXágua321,5m/esgoto566,4m/otros21,3m eJCP35% não provam manutenção versus expansão e produtividadeeconômicapor ação;COPANOR requer ponte econômica.'},'governance':{'status':'SATISFACTORY_LIMITED','reason':'ON,tagalong100%,arbitragem,auditoria e correçõestransparentes. Controleestatal51,1% e mútuos subsidiárias são conflitos; não há prova de fraude, capital inadequado ou lucroilusório.'}},
'additional_calculations':{'unadjusted_five_lower_median':394184000,'unadjusted_bound_pe_upper':4847219415/394184000,'reported2013_eps_change':3.52/4.04-1,'capex_to_ni2013':909.2/419.795,'operating_cash_minus_investing_cash2013_millions':664.649-796.828},
'materiality':'VVAL mantém admissibilidade por limite, comR$108,250m de folga real no lucro mínimo; remover2009 não reduz a janela, pois fica como menosinfinito. VQprincipal deve continuar sem nova compra enquanto duas dimensões materiaisND. Sem carteiras/retornos calculados.','specific_pending':['Retorno econômico dos projetos por safra, com ativos emoperação, tarifas, manutenção/expansão e custo de capitalPIT.','Reconciliação do crescimento por ação comCAPEX e retornoincremental normalizado; não exigirFCLpositivotodosanos.','Avaliação de recuperabilidade/sustentabilidade dos mútuos e concessõesCOPANOR.']}
]
result={'sealed_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'stage':'FINAL_2014_SEALED_BEFORE_ANY_2025_READ','independence':'Revisão adversarial formada com protocolo redigido, decisões e provas primárias dos três pacotes2014. Não li implementação, .pr4-work, retornos, resultados, checkpoints, outros pareceres, GitHub ou notícias retrospectivas. Não recalculei carteiras.2025 não foi aberto antes deste selo.','supplement_disclosure':'A raiz corrigiu transporte do originalBRGAAP2011 e forneceu IPCA primário antes deste parecer; sem sugestão de juízo. A omissão inicial foi preservada no arquivo material_initial_transport_finding_2014_before_supplement.json. Nenhum feedback de mérito foi usado.','status_semantics':'PASS=decisão auditada suportada, incluindoINDETERMINATEcorretamente preservado;UNRESOLVED=lacunadeprova material;ISSUE=erro comprovado. Não são etiquetas de retorno nem promoção de B00S.','reports':reports,'files_read':ledger,'limits':['Cotações congeladas não confrontadas com originalCOTAHIST ausente.','Hashes de todosPDFs descompactados conferidos; páginas consultadas via extração congelada. Não foi feita inspeção visual de todosPDFs.','Busca automatizada nas extrações não equivale a leitura humana integral de todaspáginas.','ZIPIBGE conferido porhash; conteúdoPDF não extraído porfalta de biblioteca disponível. SGS433 e recibometadadospré-corte foram recalculados.']}
p=OUT/'material_review_2014_sealed.json'
with p.open('x') as f:json.dump(result,f,ensure_ascii=False,indent=2,allow_nan=False)
lines=['Parecer independente2014, selado antes de2025','',result['independence'],'',result['supplement_disclosure'],'','|Caso|Auditoria|VVAL|VQ|P/L recomposto|','|---|---|---|---|---|']
for r in reports:
 lines.append(f"|{r['case']}|{r['audit_status']}|{r['admission_review']['VVAL']}|{r['admission_review']['VQ']}|{r['calculation']['pe_or_pe_upper']:.9f}|")
for r in reports:
 lines.extend(['',r['case']+' — '+r['audit_status']+' / '+r['severity'],'',r['conclusion'],'',r['materiality'],''])
 for k,v in r['dimensions'].items():lines.append(f"- {k}: {v['status']}. {v['reason']}")
 lines.extend(['','Pendências: '+ '; '.join(r['specific_pending']),'','Provas pró/contra, hashes, recebimentos, páginas e cálculos completos noJSON selado.'])
md=OUT/'material_review_2014_sealed.md'
with md.open('x') as f:f.write('\n'.join(lines)+'\n')
seal={'sealed_utc':result['sealed_utc'],'files':{str(p):hashlib.sha256(p.read_bytes()).hexdigest(),str(md):hashlib.sha256(md.read_bytes()).hexdigest()},'no_2025_read_before_seal':True}
with (OUT/'material_review_2014_seal_receipt.json').open('x') as f:json.dump(seal,f,indent=2)
print(json.dumps(seal,indent=2));print('Statuses',[(r['case'],r['audit_status']) for r in reports])
